### ISSUE TITLE
MFF101 kind of works

### ISSUE THREAD

**Issue by fonty422** [qpit/thorlabs_apt#3]
The flipper mount (MFF101 and 102) are APT controlled, and you can certainly recognise them using this. You can even make them rotate... but only in one direction. I figure that the specific commands are missing from _APTAPI?
Any chance of including this?

`apt.list_available_devices()\n`
`[(48, 37849413)]`
`flipper_mount = apt.Motor(37849413)`

Using the `move_by` i can get it to move, but never back.

**Comment by tobiasgehring** [comment]
sure. Which calls do you need that are missing?

**Comment by fonty422** [comment]
Unfortunately, I'm not familiar enough with the language to give a definitive and clear response, but the [manual](http://www.thorlabs.hk/thorcat/ETN/MFF101-Manual.pdf) says it uses 

> the motor ‘MoveJog’ method. This method contains a parameter ‘lJogDir’ that takes values from the MOTORJOGDIRECTION enumeration to specify the direction of the move, ‘1’ for clockwise and ‘2’ for counterclockwise.
> To read the flipper position, the motor ‘LLGetStatusBits’ method is used. If bit1 is set to 1, the flipper is in the upright position, if bit 1 is set to 0, the flipper is horizontal.

Does this help?

I thought I could get around this as when I check `move_home_direction` it returns `2`, and `get_move_home_paramaters()` also returned seemingly correct values of `(2, 1, 1.0, 0.3000001013278961)`, so I figure that homing the device (as you can do via the thorlabs APT GUI in the settings section) should drive it back, but it just hangs and eventually times out with the error message:

`Moving velocity failed: Time out while waiting for hardware unit to respond.`

I also looked at a nasty work around which is changing the dc_joystick_parameters so that the direction sense was 2 instead of 1, but I couldn't seem to do that.

Hope this helps.

Thankyou

**Comment by fonty422** [comment]
Actually, perhaps it's a limit switch problem, as i note that the returned tuple for get_move_home_parameters includes a 1 for 'limiting switch' (the second item in the tuple). perhaps it needs to be false/0 in order to move?
I note that when the device is in the 'home' position, that the forward and reverse limit switches are False, but True when at the other position.
However, changing these states doesn't seem to allow for homing.
Also, the `maximum_position` and `minimum_position` are `6.0` and `0.0` respectively, however no matter where the flipper is, the read out position is always 0.0.

**Comment by tobiasgehring** [comment]
MoveJog belongs to the ActiveX control and is not available in apt.dll.

Maybe it helps to set the move home parameters. I had this problem with
the K10CR which didn't move when homing (but did so in the Thorlabs'
software. What helped was the following:

motor.set_move_home_parameters(*motor.get_move_home_parameters())

So for some reason get_move_home_parameters returned parameters that
were actually not set.

Otherwise I suggest that you drop Thorlabs an email. It seems that this
is not necessarily a problem of the python wrapper but with APT in general.

**Comment by cmoriarty** [comment]
I've got an MFF101, was there ever a solution found?  I'm seeing the same behavior, I can only seem to get the flipper to move down by calling:
`motor.move(1)`

Also, the error reported above looks like there is a copy paste typo:

`Moving velocity failed: Time out while waiting for hardware unit to respond.`

I see in core.py, the move_home function raises the exception.

**Comment by fonty422** [comment]
No, I found no direct solution. Thorlabs were no help either, as the API doesn't actually work for this device - it's more a .NET thing... I think that's what they said.

Anyway, I found a non/perfect workaround where I ended up just initialising it with a motor.move(1) on load so I knew the initial position was always up, then used an external trigger via python (and a $20 USB device) to deliver a 5V I/O to drive it in the opposite direction.
That way I can keep track of where it is and, not that it's fool proof, use 2 different functions to drive it 2 different ways.
Hope that helps.

On 16 Jun 2017, at 6:52 am, cmoriarty <notifications@github.com<mailto:notifications@github.com>> wrote:


I've got an MFF101, was there ever a solution found? I'm seeing the same behavior, I can only seem to get the flipper to move down by calling:
motor.move(1)

**Comment by cmoriarty** [comment]
@fonty422 - I found a direct solution, although I didn't use this repo.  I wrote code that directly interfaces with the usb driver ("d2xx").  I found a python wrapper for the d2xx dll called ftd2xx, which is on github and pypi.  It sounds like you have a workaround in place, although if you'd like to test out the d2xx solution, I can send along some sample code.

**Comment by fonty422** [comment]
Ooo, yes please. It would be good to have a direct control version.

Sent from my iPhone

On 21 Jun 2017, at 6:30 am, cmoriarty <notifications@github.com<mailto:notifications@github.com>> wrote:


@fonty422<https://github.com/fonty422> - I found a direct solution, although I didn't use this repo. I wrote code that directly interfaces with the usb driver ("d2xx"). I found a python wrapper for the d2xx dll called ftd2xx, which is on github and pypi. It sounds like you have a workaround in place, although if you'd like to test out the d2xx solution, I can send along some sample code.

**Comment by cmoriarty** [comment]
It's pretty crude for now, but here is the code.  I followed the setup instructions found in the thorlabs apt programmer manual.  Remember to pip install ftd2xx, and swap in your serial number (should be on your motor). 

```
import ftd2xx
import ftd2xx.defines as constants
import time

serial = b"37870466"

# Raw byte commands for "MGMSG_MOT_MOVE_JOG".
up_position = b"\x6A\x04\x00\x01\x21\x01"
down_position = b"\x6A\x04\x00\x02\x21\x01"

# Recommended d2xx setup instructions from Thorlabs.
motor = ftd2xx.openEx(serial)
print(motor.getDeviceInfo())
motor.setBaudRate(115200)
motor.setDataCharacteristics(constants.BITS_8, constants.STOP_BITS_1, constants.PARITY_NONE)
time.sleep(.05)
motor.purge()
time.sleep(.05)
motor.resetDevice()
motor.setFlowControl(constants.FLOW_RTS_CTS, 0, 0)
motor.setRts()

# Send raw bytes to USB driver.
motor.write(down_position)
motor.close()

```

**Comment by fonty422** [comment]
Great.
Is it possible to ping the current position so you know where it actually is, rather than just keep track of movements and hope it's where you think?

Sent from my iPhone

On 21 Jun 2017, at 9:25 am, cmoriarty <notifications@github.com<mailto:notifications@github.com>> wrote:


It's pretty crude for now, but here is the code. I followed the setup instructions found in the thorlabs apt programmer manual. Remember to pip install ftd2xx, and swap in your serial number (should be on your motor).

import ftd2xx
import ftd2xx.defines as constants
import time

serial = b"37870466"

# Raw byte commands for "MGMSG_MOT_MOVE_JOG".
up_position = b"\x6A\x04\x00\x01\x21\x01"
down_position = b"\x6A\x04\x00\x02\x21\x01"

# Recommended d2xx setup instructions from Thorlabs.
motor = ftd2xx.openEx(serial)
print(motor.getDeviceInfo())
motor.setBaudRate(115200)
motor.setDataCharacteristics(constants.BITS_8, constants.STOP_BITS_1, constants.PARITY_NONE)
time.sleep(.05)
motor.purge()
time.sleep(.05)
motor.resetDevice()
motor.setFlowControl(constants.FLOW_RTS_CTS, 0, 0)
motor.setRts()

# Send raw bytes to USB driver.
motor.write(down_position)
motor.close()

**Comment by cmoriarty** [comment]
There is, although I haven't got it working yet.  With the code above, each command is independant.  Meaning, if you call the up_command when the motor is already up, nothing happens.  So you don't really need to manage the state anymore, you just call the correct command when you need to.

**Comment by jkhed42** [comment]
In case anyone else is using the work around by cmoriarty and wants to ping the position you can try:

```python
def open_or_closed(motor, vrb=True):
  #determine if motor is open or closed
  clsd_stat = b'*\x04\x06\x00\x81P\x01\x00\x02\x00\x00\x90' #closed byte status
  opn_stat  = b'*\x04\x06\x00\x81P\x01\x00\x01\x00\x00\x90' #open byte status
  st_bit = b"\x29\x04\x00\x00\x21\x01" #request status bits
  
  motor.write(st_bit); 
  mot_stat = motor.read(12) #NOTE: EXACTLY 12 bits need to be read. If too many, python will freeze waiting for more. If too few, you won't get them all this time (but will get some next time you read)
  if mot_stat == opn_stat: #shutter appears to be open
    if vrb: #verbose
      print('Shutter appears to be open')
    return 1 #1 for open
  elif mot_stat == clsd_stat: #shutter appears to be closed
    if vrb: #verbose
      print('Shutter appears to be closed')
    return 0 #0 for closed
  else:
    print('I am confused about the shutter position')
    return 2 #2 for confused
```
This was working for me with our MFF102. You can find more byte level commands in the "[Thorlabs APT Controllers Host-Controller Communications Protocol](https://www.thorlabs.com/software/apt/APT_Communications_Protocol_Rev_15.pdf)" documentation.

**Comment by hududed** [comment]
> In case anyone else is using the work around by cmoriarty and wants to ping the position you can try:
> 
> ```python
> def open_or_closed(motor, vrb=True):
>   #determine if motor is open or closed
>   clsd_stat = b'*\x04\x06\x00\x81P\x01\x00\x02\x00\x00\x90' #closed byte status
>   opn_stat  = b'*\x04\x06\x00\x81P\x01\x00\x01\x00\x00\x90' #open byte status
>   st_bit = b"\x29\x04\x00\x00\x21\x01" #request status bits
>   
>   motor.write(st_bit); 
>   mot_stat = motor.read(12) #NOTE: EXACTLY 12 bits need to be read. If too many, python will freeze waiting for more. If too few, you won't get them all this time (but will get some next time you read)
>   if mot_stat == opn_stat: #shutter appears to be open
>     if vrb: #verbose
>       print('Shutter appears to be open')
>     return 1 #1 for open
>   elif mot_stat == clsd_stat: #shutter appears to be closed
>     if vrb: #verbose
>       print('Shutter appears to be closed')
>     return 0 #0 for closed
>   else:
>     print('I am confused about the shutter position')
>     return 2 #2 for confused
> ```
> 
> This was working for me with our MFF102. You can find more byte level commands in the "[Thorlabs APT Controllers Host-Controller Communications Protocol](https://www.thorlabs.com/software/apt/APT_Communications_Protocol_Rev_15.pdf)" documentation.

This is great ! it worked in python 3.7 console. However, running this in spyder ipython console I get a device error. I copy pasted the code. 

```
In [13]: open_or_closed(motor)
Traceback (most recent call last):

  File "<ipython-input-13-6f1391dd46d4>", line 1, in <module>
    open_or_closed(motor)

  File "Y:/users/Hud/MFF101_Laser_onoff_control.py", line 20, in open_or_closed
    mot_stat = motor.read(12)  # NOTE: EXACTLY 12 bits need to be read. If too many, python will freeze waiting for more. If too few, you won't get them all this time (but will get some next time you read)

  File "C:\Users\labuser\Anaconda3\envs\controller\lib\site-packages\ftd2xx\ftd2xx.py", line 154, in read
    call_ft(_ft.FT_Read, self.handle, b, nchars, c.byref(b_read))

  File "C:\Users\labuser\Anaconda3\envs\controller\lib\site-packages\ftd2xx\ftd2xx.py", line 41, in call_ft
    raise DeviceError(status)

DeviceError: INVALID_HANDLE
```

Any idea why this is happening ?

**Comment by jkhed42** [comment]
> DeviceError: INVALID_HANDLE

I was able to run `open_or_closed` in my spyder ipython console without this error. I did get this INVALID_HANDLE error though when I tried to ping the position after I had ran `motor.close()`. After opening communications with it again by running all but the last 2 lines of cmoriarty's code the error went away for me at least.
