### ISSUE TITLE
Receiving error "Thorlabs APT Initialization Failed"

### ISSUE THREAD

**Issue by LeftyAce** [qpit/thorlabs_apt#7]
Hi Tobias, thank you for this great software.

I'm trying to control a KDC101 motor controller cube, and I get an error when I try to run "import thorlabs_apt as apt":

``Traceback (most recent call last):
  File "C:\Users\Lefty\Documents\RingFixtureAutomation\ThorlabsControl.py", line 5, in <module>
    import thorlabs_apt as apt
  File "C:\Users\Lefty\AppData\Local\Programs\Python\Python35\lib\site-packages\thorlabs_apt\__init__.py", line 1, in <module>
    from .core import *
  File "C:\Users\Lefty\AppData\Local\Programs\Python\Python35\lib\site-packages\thorlabs_apt\core.py", line 1373, in <module>
    _lib = _load_library()
  File "C:\Users\Lefty\AppData\Local\Programs\Python\Python35\lib\site-packages\thorlabs_apt\core.py", line 1367, in _load_library
    raise Exception("Thorlabs APT Initialization failed.")
Exception: Thorlabs APT Initialization failed.``

I have not installed the thorlabs software, rather I have copied APT.dll from another computer. I put APT.dll in the thorlabs_apt python folder. Can you suggest any way to diagnose this error?

Thanks,

Lefty

**Comment by tobiasgehring** [comment]
Hi Lefty,

APTInit() fails. Can you find out the error code?

please replace

if (lib.APTInit() != 0):
    raise Exception("Thorlabs APT Initialization failed.")

with

res = lib.APTInit()
print("APT Init Result: {0}".format(res))
if (res != 0):
    raise Exception("Thorlabs APT Initialization failed.")

in core.py

Cheers,

Tobias

**Comment by LeftyAce** [comment]
Hi Tobias,

This is what I get:

`APT Init Result: 10054`

Thanks,

Lefty

**Comment by tobiasgehring** [comment]
COM system error.

**Comment by LeftyAce** [comment]
I "solved" the error on one computer by installing the full Thorlabs APT software package, but I don't know what was installed that fixed things.

On the computer where I did not do the full install, I only have the APT.dll file, and I get this COM error even though the controller is connected via USB.

**Comment by y293651123** [comment]
this not work for me
