### ISSUE TITLE
Exception: Moving velocity failed: Time out while waiting for hardware unit to respond.

### ISSUE THREAD

**Issue by emilyxarcher** [qpit/thorlabs_apt#9]
Dear Tobias,

I tried using your software to operate the K10CR1/M but I am getting a timeout error every time I try to run it. The software seems to be recognising the device and the motor can be operated from APT User just fine, for some reason it just doesn't want to move when the python script is run. 'trial2.py' is the file I have been trying to run and I have tried running it for different locations within the directory with no luck. I have copied the file directories and the time out error below, I hope this helps.

Thanks,
Emily

Traceback (most recent call last):

  File "<ipython-input-10-ec56502de85a>", line 1, in <module>
    runfile('C:/Users/Emily/Desktop/SummerProject/Software/thorlabsK10CR1/thorlabs_apt-master/build/lib/thorlabs_apt/trial2.py', wdir='C:/Users/Emily/Desktop/SummerProject/Software/thorlabsK10CR1/thorlabs_apt-master/build/lib/thorlabs_apt')

  File "C:\Anaconda2\lib\site-packages\spyder\utils\site\sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)

  File "C:\Anaconda2\lib\site-packages\spyder\utils\site\sitecustomize.py", line 87, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "C:/Users/Emily/Desktop/SummerProject/Software/thorlabsK10CR1/thorlabs_apt-master/build/lib/thorlabs_apt/trial2.py", line 20, in <module>
    motor.move_home(True)

  File "C:\Anaconda2\lib\site-packages\thorlabs_apt-0.1-py2.7.egg\thorlabs_apt\core.py", line 830, in move_home
    _get_error_text(err_code))

Exception: Moving velocity failed: Internal error.
//
Exception: Moving velocity failed: Time out while waiting for hardware unit to respond.

[thorlabs_apt-master.zip](https://github.com/qpit/thorlabs_apt/files/1026172/thorlabs_apt-master.zip)

**Comment by bullover** [comment]
motor.set_move_home_parameters(*motor.get_move_home_parameters()) and motor.set_velocity_parameters(*motor.get_velocity_parameters())  helped me to solve this issue.
was mentioned @  "MFF101 kind of works #3"
